This commit fixes #43089
tensorflow/docs pull request #1669
Opened 2020-09-10 02:54 UTC by guptadhaval18

Fixed 2 non-working URLs

2020-09-10 06:07 UTC, lamberta requested changes
Thanks for the fix. If you use a relative path and add the file extension then the link will work in GitHub and the website

2020-09-10 06:07 UTC, lamberta commented on site/en/guide/tf_numpy.ipynb
> +        "Tensorflow's `tf.function` works by \"trace compiling\" the code and then optimizing these traces for much faster performance. See the [Introduction to Graphs and Functions](https://www.tens
```suggestion
        "Tensorflow's `tf.function` works by \"trace compiling\" the code and then optimizing these traces for much faster performance. See the [Introduction to Graphs and Functions](./intro_to_graphs.ipynb).\n",
```

2020-09-10 06:07 UTC, lamberta commented on site/en/guide/tf_numpy.ipynb
> +        "TensorFlow NumPy uses highly optimized TensorFlow kernels that can be dispatched on CPUs, GPUs and TPUs. TensorFlow also performs many compiler optimizations, like operation fusion, which tr
```suggestion
        "TensorFlow NumPy uses highly optimized TensorFlow kernels that can be dispatched on CPUs, GPUs and TPUs. TensorFlow also performs many compiler optimizations, like operation fusion, which translate to performance and memory improvements. See [TensorFlow graph optimization with Grappler](./graph_optimization.ipynb) to learn more.\n",
```

2020-09-10 06:51 UTC, guptadhaval18 commented
@lamberta thanks for help. This is my first open source pull request.

2020-09-11 02:51 UTC, lamberta approved these changes
Thanks for the contribution and welcome!

2020-09-11 15:23 UTC, merged