Updated nmt_with_attention notebook links
tensorflow/docs pull request #1920
Opened 2021-07-17 09:05 UTC by JoKoum

2021-07-17 09:08 UTC, JoKoum commented
@googlebot I signed it!

2021-07-27 21:35 UTC, 8bitmp3 requested changes
Nice catch @JoKoum 

Let's use the full URL here (www.tensorflow.org/text/tutorials/nmt_with_attention).

Many thanks!!

2021-07-27 21:35 UTC, 8bitmp3 commented on site/en/tutorials/text/image_captioning.ipynb
> +        "Fun fact: the decoder below is identical to the one in the example for [Neural Machine Translation with Attention](../../../../../../../text/blob/master/docs/tutorials/nmt_with_attention.ipy
```suggestion
        "Fun fact: the decoder below is identical to the one in the example for [Neural Machine Translation with Attention](www.tensorflow.org/text/tutorials/nmt_with_attention).\n",
```

2021-07-27 21:35 UTC, 8bitmp3 commented on site/en/tutorials/text/image_captioning.ipynb
> +        "Congrats! You've just trained an image captioning model with attention. Next, take a look at this example [Neural Machine Translation with Attention](../../../../../../../text/blob/master/do
```suggestion
        "Congrats! You've just trained an image captioning model with attention. Next, take a look at this example [Neural Machine Translation with Attention]((www.tensorflow.org/text/tutorials/nmt_with_attention). It uses a similar architecture to translate between Spanish and English sentences. You can also experiment with training the code in this notebook on a different dataset."
```

2021-07-27 21:37 UTC, 8bitmp3 approved these changes

2021-07-28 00:07 UTC, MarkDaoust approved these changes

2021-07-28 00:11 UTC, merged

2021-07-28 15:47 UTC, 8bitmp3 commented
Good call @MarkDaoust Thanks