Update text_classification.ipynb
tensorflow/docs pull request #1964
Opened 2021-10-20 16:34 UTC by RenuPatelGoogle

updated 'preprocessing.TextVectorization' with 'tf.keras.layers.TextVectorization' in Prepare the dataset for training section.

2021-11-01 12:40 UTC, MarkDaoust requested changes
While you're here could you also remove the references to `tf.keras.preprocessing`?

- the `from tensorflow.keras import preprocessing`
- `preprocessing.text_dataset_from_directory` should be `tf.keras.utils.text_dataset_from_directory`

Thanks.

2021-11-02 14:07 UTC, RenuPatelGoogle commented
> While you're here could you also remove the references to `tf.keras.preprocessing`?
> 
> * the `from tensorflow.keras import preprocessing`
> * `preprocessing.text_dataset_from_directory` should be `tf.keras.utils.text_dataset_from_directory`
> 
> Thanks.

Updated the same as you referred. Could you please review the document again?

2021-11-02 15:27 UTC, MarkDaoust submitted a review, later dismissed

2021-11-04 20:30 UTC, 8bitmp3 commented
Let me look into the CI / Notebook lint test for you @RenuPatelGoogle Thanks for the PR!

2021-11-04 21:21 UTC, 8bitmp3 approved these changes

2021-11-05 12:11 UTC, merged