Mjahmadee patch
tensorflow/docs pull request #2116
Opened 2022-08-21 02:53 UTC by MJAHMADEE

Solve TypeError: 'type' object is not subscriptable

2022-08-22 06:47 UTC, MJAHMADEE commented
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/tensorflow/docs/pull/2116/checks?check_run_id=7935868395) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

https://stackoverflow.com/a/73427982/10682223

2022-08-22 07:35 UTC, markmcd requested changes
By importing the future annotations module, you should be able to leave the new-style type annotations in place.

2022-08-22 07:35 UTC, markmcd commented on tools/tensorflow_docs/api_generator/reference_resolver.py
> +from __future__ import annotations
This should be the only change you need to make to enable this file to be loaded in Py3.7.

2022-08-22 07:35 UTC, markmcd commented on tools/tensorflow_docs/api_generator/reference_resolver.py
> -      *,
Leave the `*` kwonly operator there please

2022-08-22 07:35 UTC, markmcd commented on tools/tensorflow_docs/api_generator/reference_resolver.py
> -      physical_path: Optional[dict[str, str]] = None,
Leave `physical_path` in place; removing it breaks the method as it's still referenced.

2022-12-13 22:08 UTC, 8bitmp3 commented
Closing for now until there's an update following @markmcd 's review and comments (Aug 22)

2022-12-13 22:08 UTC, closed without merging