Update GPU Support For Windows Native
tensorflow/docs pull request #2153
Opened 2022-11-22 14:16 UTC by chunduriv

Since TF 2.11 does't support GPU on Windows native,  updated `python3 -m pip install tensorflow` to `python3 -m pip install tensorflow=2.10` else it will always install latest release and it doesn't recognize the GPU.

2022-11-22 14:33 UTC, MarkDaoust requested changes

2022-11-22 14:33 UTC, MarkDaoust commented on site/en/install/pip.md
> +    python3 -m pip install tensorflow=2.10 # Anything above 2.10 is not supported on the GPU on Windows Native
```suggestion
    # Anything above 2.10 is not supported on the GPU on Windows Native
    python3 -m pip install "tensorflow<2.11"
```

2022-11-22 14:33 UTC, MarkDaoust commented on site/en/install/pip.md
> +    pip install tensorflow=2.10 # Anything above 2.10 is not supported on the GPU on Windows Native
```suggestion
    # Anything above 2.10 is not supported on the GPU on Windows Native
    pip install "tensorflow<2.11" 
```

2022-11-22 14:34 UTC, MarkDaoust approved these changes

2022-11-23 20:35 UTC, 8bitmp3 approved these changes
Thanks @chunduriv @MarkDaoust

2022-11-28 21:20 UTC, MarkDaoust approved these changes

2022-11-29 01:04 UTC, merged