Minor fix in type hint and stringdoc
tensorflow/docs pull request #2205
Opened 2023-03-15 21:02 UTC by felipetovarhenao

*predict_next_note* currently says it returns an ID, where the return type is int, but it actually returns a tuple.

2023-03-16 07:27 UTC, markmcd requested changes
Thanks for the patch!

2023-03-16 07:27 UTC, markmcd commented on site/en/tutorials/audio/music_generation.ipynb
> +        "    temperature: float = 1.0) -> Tuple:\n",
```suggestion
        "    temperature: float = 1.0) -> tuple[int, float, float]:\n",
```

Two things here:
- prefer the built-in `tuple` over `typing.Tuple`, and
- provide type information about the tuple contents.

And the `Tuple` import on line 148 can be removed too.

2023-03-16 13:00 UTC, felipetovarhenao commented
@markmcd Suggested changed added!

2023-03-20 05:06 UTC, markmcd approved these changes
LG, thanks

2023-03-21 18:03 UTC, merged