Update broken links in function.ipynb
tensorflow/docs pull request #2223
Opened 2023-05-02 10:00 UTC by synandi

Fixes https://github.com/tensorflow/tensorflow/issues/60459
Fix broken links in lines 64, 441 and 975

2023-06-07 20:26 UTC, sachinprasadhs approved these changes

2023-06-08 12:52 UTC, MarkDaoust requested changes

2023-06-08 12:52 UTC, MarkDaoust commented on site/en/guide/function.ipynb
> +        "To learn about how to export and load a `Function`, see the [SavedModel guide](https://github.com/tensorflow/docs/blob/master/site/en/guide/saved_model.ipynb). To learn more about graph opti
```suggestion
        "To learn about how to export and load a `Function`, see the [SavedModel guide](saved_model.ipynb). To learn more about graph optimizations that are performed after tracing, see the [Grappler guide](graph_optimization.ipynb). To learn how to optimize your data pipeline and profile your model, see the [Profiler guide](profiler.md)."
```

2023-06-08 12:53 UTC, MarkDaoust commented
Thanks for the fixes. 

Please prefer relative links where possible, and tensorflow.org links where relative links are not possible.

2023-07-18 20:44 UTC, 8bitmp3 approved these changes

2023-07-18 20:48 UTC, 8bitmp3 commented
@synandi Can you check the CLA and sign it (link to details: https://github.com/tensorflow/docs/pull/2223/checks?check_run_id=15147043836 itis the same as the "Details" link below where it says "cla/google  Failing.... Missing CLA...").

2023-12-01 08:28 UTC, gbaned commented
Closing this PR due to changes are merged through [PR#2269](https://github.com/tensorflow/docs/pull/2269)  Thank you!

2023-12-01 15:59 UTC, 8bitmp3 commented
> Please close this PR because changes are merged through https://github.com/tensorflow/docs/pull/2269 Thank you!
@gbaned :+1:

2023-12-01 15:59 UTC, closed without merging