fixed the tf issue #74564
tensorflow/docs pull request #2322
Opened 2024-08-28 12:12 UTC by sanskarmodi8

I looked into the issue and found out that after the evaluation we are getting a list of size 4 where only the last one is the accuracy of the export_model. So ignored all the other output to only get the required loss and accuracy

2024-08-29 20:52 UTC, MarkDaoust requested changes

2024-08-29 20:52 UTC, MarkDaoust commented on site/en/tutorials/keras/text_classification.ipynb
> +        "_, _, loss, accuracy = export_model.evaluate(raw_test_ds)\n",
```suggestion
        "metrics = export_model.evaluate(raw_test_ds, return_dict=True)\n",
```

2024-08-29 20:52 UTC, MarkDaoust commented on site/en/tutorials/keras/text_classification.ipynb
>          "print(accuracy)"
```suggestion
        "print(metrics)"
```

2024-08-29 20:53 UTC, MarkDaoust approved these changes

2024-08-29 20:54 UTC, MarkDaoust commented
Thanks for the fix! 

I actually always prefer `return_dict=True` because then the response labels each output. It makes it much clearer what's what.

2024-08-30 02:07 UTC, merged

2024-08-30 02:18 UTC, sanskarmodi8 commented
> Thanks for the fix! 
> 
> I actually always prefer `return_dict=True` because then the response labels each output. It makes it much clearer what's what.

Thank you, Mark! I'll keep that in mind and make sure to use return_dict=True moving forward.
It definitely helps in making the output clearer.